// Module included in the following assemblies:
//
// * machine_management/user_infra/adding-bare-metal-compute-user-infra.adoc
// * post_installation_configuration/node-tasks.adoc
ifeval::["{context}" == "multi-architecture-configuration"]
:multi:
endif::[]

:_content-type: PROCEDURE
[id="machine-user-infra-machines-iso_{context}"]
= Creating {op-system} machines using virt-install

You can create more {op-system-first} compute machines for your IBM Z and IBM® LinuxONE using virt-install.

.Prerequisites

* At least one LPAR running on {op-system-base} 8.7 or later with KVM, referred to as {op-system-base} KVM host in this procedure.
* The KVM/QEMU hypervisor is installed on the {op-system-base} KVM host.
* A domain name server (DNS) that can perform hostname and reverse lookup for the new compute node.
* An HTTP or HTTPS server is set up.
* You must have the OpenShift CLI (`oc`) installed.

.Procedure

. Extract the Ignition config file from the cluster by running the following command:
+
[source,terminal]
----
$ oc extract -n openshift-machine-api secret/worker-user-data-managed --keys=userData --to=- > worker.ign
----

. Upload the `worker.ign` Ignition config file you exported from your cluster to your HTTP server. Note the URL of this file.

. You can validate that the Ignition file is available on the URL. The following example gets the Ignition file for the compute node:
+
[source,terminal]
----
$ curl -k http://<HTTP_server>/worker.ign
----

. Download the {op-system-base} live kernel, initramfs, and rootfs files by running to following commands:
+
[source,terminal]
----
curl -LO $(oc -n openshift-machine-config-operator get configmap/coreos-bootimages -o jsonpath='{.data.stream}' \
| jq -r '.architectures.s390x.artifacts.metal.formats.pxe.kernel.location')
----
+
[source,terminal]
----
curl -LO =$(oc -n openshift-machine-config-operator get configmap/coreos-bootimages -o jsonpath='{.data.stream}' \
| jq -r '.architectures.s390x.artifacts.metal.formats.pxe.initramfs.location')
----
+
[source,terminal]
----
curl -LO $(oc -n openshift-machine-config-operator get configmap/coreos-bootimages -o jsonpath='{.data.stream}' \
| jq -r '.architectures.s390x.artifacts.metal.formats.pxe.rootfs.location')
----

. Move the downloaded {op-system-base} live kernel, initramfs, and rootfs to your HTTP server before you launch `virt-install`.

. Create the new KVM guest nodes using the {op-system-base} live kernel, initramfs, rootfs, and Ignition files, and adjusted parm line arguments.
** For `--location`, specify the URL location of the kernel/initrd on the HTTP server.
** For `coreos.inst.ignition_url=`, specify the `worker.ign` Ignition URL for the machine role. Only HTTP and HTTPS protocols are supported.
** For `coreos.live.rootfs_url=`, specify the URL location of the rootfs on the HTTP server. Only HTTP and HTTPS protocols are supported.
+
[source,terminal]
----
$ virt-install \
   --connect qemu:///system \
   --name {vn_name} \
   --autostart \
   --os-variant rhel9.0 \
   --cpu host \
   --vcpus {vcpus} \
   --memory {memory_mb} \
   --disk {vn_name}.qcow2,size={image_size | default(100,true)} \
   --network network={virt_network_parm} \
   --location {media_location},kernel={rhcos_kernel},initrd={rhcos_initrd} \
   --extra-args "rd.neednet=1" \
   --extra-args "coreos.inst.ins0tall_dev=/dev/vda" \
   --extra-args "coreos.inst.ignition_url={worker_ign}" \
   --extra-args "coreos.live.rootfs_url={rhcos_rootfs}" \
   --extra-args "ip={ip}::{default_gateway}:{subnet_mask_length}:{vn_name}::none:{MTU} nameserver={dns}" \
   --extra-args "console=ttysclp0" \
   --noautoconsole \
   --wait
----

. Continue to create more compute machines for your cluster.
